In [1]:
# Initializing imports.
from pathlib import Path
import os
import zipfile
import requests,io
import pandas as pd
import datetime as dt

In [2]:
# Assigned local path and read in Weather csv file.
file_path = Path("OHAREWEATHERDATA_2019.csv")
chi_weather = pd.read_csv('OHAREWEATHERDATA_2019.csv', infer_datetime_format = True)
chi_weather

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,...,WSF2,WSF5,WT01,WT02,WT03,WT04,WT05,WT06,WT08,WT09
0,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/1/2019,7.61,0.01,0.1,0.0,31,34,26,...,16.1,21.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/2/2019,8.72,0.01,0.1,0.0,28,30,26,...,19.9,29.1,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/3/2019,11.63,0.00,0.0,0.0,29,38,24,...,17.0,27.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/4/2019,8.05,0.00,0.0,0.0,37,48,31,...,14.1,19.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/5/2019,8.28,0.00,0.0,0.0,39,52,32,...,18.1,23.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/6/2019,11.63,0.00,0.0,0.0,38,40,30,...,21.9,29.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/7/2019,15.66,0.44,0.0,0.0,44,53,40,...,25.1,36.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/8/2019,14.54,0.00,0.0,0.0,41,45,24,...,32.0,49.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/9/2019,13.65,0.00,0.0,0.0,23,24,15,...,23.0,33.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/10/2019,4.47,0.00,0.0,0.0,18,24,14,...,14.1,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/11/2019,4.92,0.00,0.0,0.0,23,30,17,...,13.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/12/2019,11.41,0.12,2.2,0.0,30,32,29,...,21.0,30.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
12,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/13/2019,12.53,0.01,0.3,2.0,30,31,25,...,19.9,25.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/14/2019,8.28,0.00,0.0,2.0,25,27,23,...,14.1,19.9,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN
14,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/15/2019,11.18,0.00,0.0,1.2,26,32,24,...,21.0,31.1,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
15,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/16/2019,9.40,0.00,0.0,1.2,31,34,28,...,16.1,21.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
16,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/17/2019,5.59,0.00,0.0,0.0,30,35,28,...,12.1,14.1,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
17,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/18/2019,10.51,0.12,1.3,0.0,30,31,27,...,19.9,25.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/19/2019,20.13,0.18,3.7,3.9,26,28,11,...,31.1,38.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
19,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/20/2019,13.42,0.00,0.0,5.1,12,14,4,...,21.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/21/2019,8.50,0.00,0.1,5.1,9,17,3,...,17.0,23.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
21,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/22/2019,9.40,0.18,0.5,5.1,19,33,13,...,19.9,29.1,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN
22,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/23/2019,9.84,0.22,1.0,3.9,29,34,19,...,17.0,23.9,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN
23,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/24/2019,11.63,0.00,0.4,5.1,17,22,2,...,23.9,35.1,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
24,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/25/2019,9.40,0.03,0.7,5.1,1,5,-6,...,18.1,27.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/26/2019,5.82,0.06,1.7,7.1,2,12,-7,...,14.1,19.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/27/2019,6.93,0.00,0.0,7.1,4,11,-5,...,15.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/28/2019,12.75,0.53,5.0,9.1,18,34,8,...,25.9,35.1,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0
28,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/29/2019,14.54,0.00,0.3,9.8,6,10,-10,...,29.1,44.1,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0
29,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",1/30/2019,15.21,0.00,0.0,7.9,-15,-10,-23,...,23.9,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/2/2019,10.29,0.00,0.0,0.0,32,35,29,...,21.0,29.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/3/2019,11.86,0.00,0.0,0.0,32,40,29,...,18.1,25.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/4/2019,12.08,0.00,0.0,0.0,37,43,31,...,25.1,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/5/2019,6.71,0.00,0.0,0.0,36,45,27,...,13.0,18.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/6/2019,9.84,0.00,0.0,0.0,38,42,27,...,25.9,35.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/7/2019,8.28,0.00,0.0,0.0,31,37,25,...,16.1,21.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/8/2019,10.29,0.00,0.0,0.0,38,47,34,...,19.9,28.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
342,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/9/2019,12.97,0.05,0.0,0.0,46,47,24,...,28.0,44.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/10/2019,11.86,0.00,0.0,0.0,22,24,14,...,21.9,31.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/11/2019,7.38,0.00,0.1,0.0,18,24,13,...,19.9,29.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/12/2019,12.30,0.00,0.0,0.0,28,45,19,...,23.9,35.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/13/2019,4.92,0.00,0.0,0.0,40,45,34,...,13.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/14/2019,9.40,0.00,0.0,0.0,33,35,24,...,19.9,29.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/15/2019,6.04,0.00,0.0,0.0,24,26,19,...,16.1,21.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/16/2019,6.71,0.01,0.3,0.0,26,30,24,...,14.1,17.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/17/2019,10.74,0.00,0.0,0.0,25,29,19,...,21.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
351,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/18/2019,8.72,0.00,0.0,0.0,20,27,10,...,17.0,25.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/19/2019,8.50,0.00,0.0,0.0,23,35,15,...,19.9,28.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/20/2019,5.59,0.00,0.0,0.0,30,41,23,...,13.0,17.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
354,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/21/2019,7.61,0.00,0.0,0.0,38,47,32,...,15.0,19.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/22/2019,10.07,0.00,0.0,0.0,40,52,33,...,16.1,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/23/2019,7.61,0.00,0.0,0.0,42,52,33,...,15.0,21.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/24/2019,8.05,0.00,0.0,0.0,40,55,30,...,17.0,23.9,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN
358,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/25/2019,8.72,0.00,0.0,0.0,47,57,37,...,17.0,25.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/26/2019,11.18,0.00,0.0,0.0,56,61,37,...,18.1,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/27/2019,7.16,0.00,0.0,0.0,37,37,28,...,17.0,23.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/28/2019,6.93,0.28,0.0,0.0,34,48,27,...,14.1,17.0,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN
362,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/29/2019,10.96,0.93,0.0,0.0,52,57,47,...,21.9,31.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/30/2019,17.67,0.09,0.7,0.0,38,47,27,...,30.0,45.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",12/31/2019,14.54,0.08,0.8,2.0,26,28,24,...,30.0,42.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# Dropped the columns that we do not need in final dataframe.
chi_weather=chi_weather.drop(columns = ['STATION','NAME','AWND', 'SNOW','SNWD','TMAX','TMIN','WDF2', 'WDF5','WSF2', 'WSF5', 'WT01', 'WT02', 'WT03','WT04','WT05','WT06','WT08','WT09'])

In [42]:
# Converted the dates into the datetime format.
chi_weather['DATE']=pd.to_datetime(chi_weather["DATE"])

In [43]:
chi_weather.head()

        DATE  PRCP  TAVG
0 2019-01-01  0.01    31
1 2019-01-02  0.01    28
2 2019-01-03  0.00    29
3 2019-01-04  0.00    37
4 2019-01-05  0.00    39

In [26]:
# Created a new daily date dataframe with the date range of 1/1/19 to 12/31/19.
weeks_2019_weather = pd.date_range('2019-1-1', '2019-12-31', freq = "D").to_series()

In [27]:
# Got the number of the week for each date on daily data frame.
weeks_2019_weather = weeks_2019_weather.dt.week

In [28]:
# Converted new Weeks series in  to dataframe, reset the index and dropped additional index column and renamed 'Week' to column.
Weeks_2019_df = weeks_2019_weather.to_frame().reset_index().drop(columns=['index']).rename(columns={'week':'Week'})

In [31]:
Weeks_2019_df

      0
0     1
1     1
2     1
3     1
4     1
5     1
6     2
7     2
8     2
9     2
10    2
11    2
12    2
13    3
14    3
15    3
16    3
17    3
18    3
19    3
20    4
21    4
22    4
23    4
24    4
25    4
26    4
27    5
28    5
29    5
..   ..
335  49
336  49
337  49
338  49
339  49
340  49
341  49
342  50
343  50
344  50
345  50
346  50
347  50
348  50
349  51
350  51
351  51
352  51
353  51
354  51
355  51
356  52
357  52
358  52
359  52
360  52
361  52
362  52
363   1
364   1

[365 rows x 1 columns]

In [38]:
# Changed the column name to week.
new_names = ['week']
Weeks_2019_df.columns = new_names
Weeks_2019_df

     week
0       1
1       1
2       1
3       1
4       1
5       1
6       2
7       2
8       2
9       2
10      2
11      2
12      2
13      3
14      3
15      3
16      3
17      3
18      3
19      3
20      4
21      4
22      4
23      4
24      4
25      4
26      4
27      5
28      5
29      5
..    ...
335    49
336    49
337    49
338    49
339    49
340    49
341    49
342    50
343    50
344    50
345    50
346    50
347    50
348    50
349    51
350    51
351    51
352    51
353    51
354    51
355    51
356    52
357    52
358    52
359    52
360    52
361    52
362    52
363    52
364    52

[365 rows x 1 columns]

In [33]:
# Find out the weeks data types
Weeks_2019_df.dtypes

week    int64
dtype: object

In [34]:
# Since 12/30/31 is technically Week #1 of Jan. 2020, we need to convert to Week 53 by doing it we will prevent adding values to Week 1 data
Weeks_2019_df.iloc[[363],0]=52

In [35]:
# Same with this date, since 12/31/31 is technically Week #1 of Jan. 2020, we needed to convert to Week 53. This will prevent adding values to Week 1 data.

Weeks_2019_df.iloc[[364],0]=52

In [36]:
# Final Weather dataframes by week:
Weeks_2019_df

     week
0       1
1       1
2       1
3       1
4       1
5       1
6       2
7       2
8       2
9       2
10      2
11      2
12      2
13      3
14      3
15      3
16      3
17      3
18      3
19      3
20      4
21      4
22      4
23      4
24      4
25      4
26      4
27      5
28      5
29      5
..    ...
335    49
336    49
337    49
338    49
339    49
340    49
341    49
342    50
343    50
344    50
345    50
346    50
347    50
348    50
349    51
350    51
351    51
352    51
353    51
354    51
355    51
356    52
357    52
358    52
359    52
360    52
361    52
362    52
363    52
364    52

[365 rows x 1 columns]

In [44]:
# Combined the week dataframe with the rest of the dataframe. Each date now has its respective week number.
joined_weather_n_weeks_df = pd.concat([Weeks_2019_df,chi_weather], axis="columns", join="inner")

In [45]:
# Final Avg. Weather dataframe by week:
joined_weather_n_weeks_df

     week       DATE  PRCP  TAVG
0       1 2019-01-01  0.01    31
1       1 2019-01-02  0.01    28
2       1 2019-01-03  0.00    29
3       1 2019-01-04  0.00    37
4       1 2019-01-05  0.00    39
5       1 2019-01-06  0.00    38
6       2 2019-01-07  0.44    44
7       2 2019-01-08  0.00    41
8       2 2019-01-09  0.00    23
9       2 2019-01-10  0.00    18
10      2 2019-01-11  0.00    23
11      2 2019-01-12  0.12    30
12      2 2019-01-13  0.01    30
13      3 2019-01-14  0.00    25
14      3 2019-01-15  0.00    26
15      3 2019-01-16  0.00    31
16      3 2019-01-17  0.00    30
17      3 2019-01-18  0.12    30
18      3 2019-01-19  0.18    26
19      3 2019-01-20  0.00    12
20      4 2019-01-21  0.00     9
21      4 2019-01-22  0.18    19
22      4 2019-01-23  0.22    29
23      4 2019-01-24  0.00    17
24      4 2019-01-25  0.03     1
25      4 2019-01-26  0.06     2
26      4 2019-01-27  0.00     4
27      5 2019-01-28  0.53    18
28      5 2019-01-29  0.00     6
29      5 2019-01-30  0.00   -15
..    ...        ...   ...   ...
335    49 2019-12-02  0.00    32
336    49 2019-12-03  0.00    32
337    49 2019-12-04  0.00    37
338    49 2019-12-05  0.00    36
339    49 2019-12-06  0.00    38
340    49 2019-12-07  0.00    31
341    49 2019-12-08  0.00    38
342    50 2019-12-09  0.05    46
343    50 2019-12-10  0.00    22
344    50 2019-12-11  0.00    18
345    50 2019-12-12  0.00    28
346    50 2019-12-13  0.00    40
347    50 2019-12-14  0.00    33
348    50 2019-12-15  0.00    24
349    51 2019-12-16  0.01    26
350    51 2019-12-17  0.00    25
351    51 2019-12-18  0.00    20
352    51 2019-12-19  0.00    23
353    51 2019-12-20  0.00    30
354    51 2019-12-21  0.00    38
355    51 2019-12-22  0.00    40
356    52 2019-12-23  0.00    42
357    52 2019-12-24  0.00    40
358    52 2019-12-25  0.00    47
359    52 2019-12-26  0.00    56
360    52 2019-12-27  0.00    37
361    52 2019-12-28  0.28    34
362    52 2019-12-29  0.93    52
363    52 2019-12-30  0.09    38
364    52 2019-12-31  0.08    26

[365 rows x 4 columns]

In [ ]:
# 
Divvy_Trips_2019_Q1_link = 'https://divvy-tripdata.s3.amazonaws.com/Divvy_Trips_2019_Q1.zip'
Divvy_Trips_2019_Q2_link = 'https://divvy-tripdata.s3.amazonaws.com/Divvy_Trips_2019_Q2.zip'
Divvy_Trips_2019_Q3_link = 'https://divvy-tripdata.s3.amazonaws.com/Divvy_Trips_2019_Q3.zip'
Divvy_Trips_2019_Q4_link = 'https://divvy-tripdata.s3.amazonaws.com/Divvy_Trips_2019_Q4.zip'

In [ ]:
#
file_path = 'https://www.kaggle.com/chicago/chicago-beach-swim,-weather,-lab-data?select=beach-weather-stations-automated-sensors.csv'
df = pd.read_csv('https://www.kaggle.com/chicago/chicago-beach-swim,-weather,-lab-data?select=beach-weather-stations-automated-sensors.csv')
df.head()

In [ ]:
# 
getfolder1 = requests.get(Divvy_Trips_2019_Q1_link)
getfolder2 = requests.get(Divvy_Trips_2019_Q2_link)
getfolder3 = requests.get(Divvy_Trips_2019_Q3_link)
getfolder4 = requests.get(Divvy_Trips_2019_Q4_link)

In [ ]:
getfolder5 = requests.get(chi_weather_link)

In [ ]:
#
unzipfolder1 = zipfile.ZipFile(io.BytesIO(getfolder1.content))
unzipfolder2 = zipfile.ZipFile(io.BytesIO(getfolder2.content))
unzipfolder3 = zipfile.ZipFile(io.BytesIO(getfolder3.content))
unzipfolder4 = zipfile.ZipFile(io.BytesIO(getfolder4.content))

In [ ]:
unzipfolder5 = zipfile.ZipFile(io.BytesIO(getfolder5.content))

In [ ]:
#
unzipfolder1.extractall('./Q1/Divvy_Trips_2019_Q1')
unzipfolder2.extractall('./Q2/Divvy_Trips_2019_Q2')
unzipfolder3.extractall('./Q3/Divvy_Trips_2019_Q3')
unzipfolder4.extractall('./Q4/Divvy_Trips_2019_Q4')

In [ ]:
# 
os.rename("./Q1/Divvy_Trips_2019_Q1/Divvy_Trips_2019_Q1","./Q1/Divvy_Trips_2019_Q1/Divvy_Trips_2019_Q1.csv")
os.rename("./Q2/Divvy_Trips_2019_Q2/Divvy_Trips_2019_Q2","./Q2/Divvy_Trips_2019_Q2/Divvy_Trips_2019_Q2.csv")

In [ ]:
# 
Q1_df = pd.read_csv('./Q1/Divvy_Trips_2019_Q1/Divvy_Trips_2019_Q1.csv')
Q2_df = pd.read_csv('./Q2/Divvy_Trips_2019_Q2/Divvy_Trips_2019_Q2.csv')
Q3_df = pd.read_csv('./Q3/Divvy_Trips_2019_Q3/Divvy_Trips_2019_Q3.csv')
Q4_df = pd.read_csv('./Q4/Divvy_Trips_2019_Q4/Divvy_Trips_2019_Q4.csv')

In [ ]:
# 
Q2_df = Q2_df.rename(
    columns={'01 - Rental Details Rental ID' : 'trip_id'
             , '01 - Rental Details Local Start Time' : 'start_time'
             ,'01 - Rental Details Local End Time' : 'end_time'
             ,'01 - Rental Details Bike ID' : 'bikeid'
             ,'01 - Rental Details Duration In Seconds Uncapped' : 'tripduration'
             ,'03 - Rental Start Station ID' : 'from_station_id'
             ,'03 - Rental Start Station Name' : 'from_station_name'
             ,'02 - Rental End Station ID' : 'to_station_id'
             ,'02 - Rental End Station Name' : 'to_station_name'
             ,'User Type' : 'usertype'
             ,'Member Gender' : 'gender'
             ,'05 - Member Details Member Birthday Year' : 'birthyear'}
)

In [ ]:
# 
joined_Divvy_data = Q1_df.append([Q2_df,Q3_df,Q4_df], ignore_index=True, sort=False)

In [ ]:
# 
joined_Divvy_data.drop(columns=[
    'trip_id'
    , 'end_time', 'bikeid'
    , 'from_station_id'
    , 'from_station_name'
    , 'to_station_id'
    ,'to_station_name'], inplace=True)

In [ ]:
# 
joined_Divvy_data_split = joined_Divvy_data['start_time'].str.split(" ", n = 1, expand = True)

In [ ]:
# 
joined_Divvy_data_split = joined_Divvy_data_split.rename(columns={0:'Date'})

In [ ]:
# 
joined_Divvy_data_split.drop(columns=[1], inplace=True)

In [ ]:
# 
joined_Divvy_data_split['Date']=pd.to_datetime(joined_Divvy_data_split.Date)

In [ ]:
# 
joined_Divvy_data_split['Date']=joined_Divvy_data_split['Date'].dt.strftime('%m/%d/%Y')

In [ ]:
# 
joined_Divvy_data_all = pd.concat([joined_Divvy_data, joined_Divvy_data_split], axis="columns", join="inner")

In [ ]:
# 
joined_Divvy_data_all.drop(columns=['start_time'], inplace=True)

In [ ]:
# 
joined_Divvy_data_all = joined_Divvy_data_all.rename(columns={'usertype':'User_Type', 'tripduration':'Trip_Duration_min', 'gender':'Gender', 'birthyear':'Birth_Year'})

In [ ]:
# Cleansing nulls from Joined Dataframe by replacing NAN values with empty strings.
Full_Divvy_data = joined_Divvy_data_all.fillna("")

In [ ]:
# 
Full_Divvy_data = Full_Divvy_data[['Date', 'User_Type', 'Trip_Duration_min', 'Gender', 'Birth_Year']]
Full_Divvy_data.head()

In [ ]:
# 
Total_2019_Users = joined_Divvy_data_all.groupby('Date').User_Type.count().to_frame().rename(columns={'User_Type':'Total_2019_Users'}).reset_index()
Total_2019_Users.head()

In [ ]:
# 
Weeks_2019 = pd.date_range('2018-12-31', '2019-12-30', freq='D').to_series()

In [ ]:
# 
Weeks_2019 = Weeks_2019.dt.isocalendar().week

In [ ]:
# 
Weeks_2019_df = Weeks_2019.to_frame().reset_index().drop(columns=['index']).rename(columns={'week':'Week'})

In [ ]:
# 
Weeks_2019_df.iloc[[364],['Week']]=52

In [ ]:
# 
Weeks_2019_df.loc[len(Weeks_2019_df.index)]=52

In [ ]:
# 
Weeks_2019_df = Weeks_2019_df.drop(labels=0, axis=0)

In [ ]:
# 
Weeks_2019_df = Weeks_2019_df.reset_index().drop(columns=['index'])

In [ ]:
# 
Weekly_df = pd.concat([Weeks_2019_df, Total_2019_Users], axis="columns", join="inner")
Weekly_df

In [ ]:
# 
Weekly_Divvy_Users_df = Weekly_df.groupby('Week').Total_2019_Users.sum().reset_index()

In [ ]:
# 
Weekly_Divvy_Users_df

In [ ]:
# 
Weekly_Divvy_Users_df.to_csv(r'../Weekly_Divvy_Users.csv', index=False)

In [ ]:
# 
Divvy_data = joined_Divvy_data_all
Divvy_data.dropna(inplace=True)

In [ ]:
# 
Divvy_data['Birth_Year'] = Divvy_data['Birth_Year'].astype(int)

In [ ]:
# 
Divvy_data['Trip_Duration_min']=Divvy_data['Trip_Duration_min'].str.replace('.,','')

In [ ]:
# 
Divvy_data['Trip_Duration_min'] = Divvy_data['Trip_Duration_min'].astype(float).astype(int)

In [ ]:
# 
Divvy_data['Trip_Duration_min'] = Divvy_data['Trip_Duration_min']/60

In [ ]:
# 
Divvy_data['Trip_Duration_min'] = Divvy_data['Trip_Duration_min'].round(1).astype(float)

In [ ]:
Divvy_data['Date'] = pd.to_datetime(Divvy_data.Date)

In [ ]:
# 
Divvy_data = Divvy_data[['Date', 'User_Type', 'Trip_Duration_min', 'Gender', 'Birth_Year']]
Divvy_data.head()

In [ ]:
# 
Divvy_data

In [ ]:
# 
Divvy_data.dtypes

In [ ]:
#

In [ ]:
#

In [ ]:
#

In [ ]:
#

In [ ]:
#

In [ ]:
#

In [ ]:
#

In [ ]:
#

In [ ]:
#

In [ ]:
#

In [ ]:
#